#!/bin/bash

BASE=$(dirname $(readlink -f $0))

PBF=$(readlink -f $1)
SHP=$(readlink -f $2)
OUTFILE=$(readlink -f $3)

time docker run -i --rm \
	-v ${BASE}:/current \
	-v $(dirname ${OUTFILE}):/output \
	-v $(dirname ${PBF}):/pbf \
	-v $(dirname ${SHP}):/shp \
	-e SHP=/shp/$(basename ${SHP}) \
        -e PBF=/pbf/$(basename ${PBF}) \
	-e OUTFILE=/output/$(basename ${OUTFILE}) \
        flo/postgis \
	/current/withindocker-process

