#!/bin/bash

BASE=$(dirname $(readlink -f $0))

PBF=$1
SHP=$2
OUTFILE=$3

time docker run -it --rm \
	-v ${BASE}:/current \
	-v $(dirname ${OUTFILE}):/output \
	-v $(dirname ${PBF}):/pbf \
	-v $(dirname ${SHP}):/shp \
	-e SHP=/shp/$(basename ${SHP}) \
        -e PBF=/pbf/$(basename ${PBF}) \
	-e OUTFILE=/output/$(basename ${OUTFILE}) \
        flo/postgis \
	/current/withindocker-process

